# Generated by Django 4.2.21 on 2025-05-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0002_alter_permission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='菜单名称')),
                ('order', models.IntegerField(default=0, verbose_name='菜单排序')),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='菜单路径')),
                ('component', models.CharField(blank=True, max_length=128, null=True, verbose_name='组件路径')),
                ('query', models.CharField(blank=True, max_length=128, null=True, verbose_name='路由参数')),
                ('route_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='路由名称')),
                ('is_frame', models.BooleanField(default=False, verbose_name='是否内嵌')),
                ('is_cache', models.BooleanField(default=False, verbose_name='是否缓存')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menu', verbose_name='父菜单')),
                ('permissions', models.ManyToManyField(blank=True, help_text='菜单关联的权限', related_name='menus', to='permission.permission', verbose_name='菜单权限')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['order'],
            },
        ),
    ]
