# Generated by Django 4.2.21 on 2025-05-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
