# Generated by Django 4.2.21 on 2025-05-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_parent_id_menu_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='permissions',
        ),
    ]
