# Generated by Django 4.2.21 on 2025-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_permissions'),
        ('role', '0002_alter_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='roles', to='menu.menu', verbose_name='菜单'),
        ),
    ]
