# Generated by Django 4.2.21 on 2025-05-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_permissions'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='role.role', verbose_name='拥有角色'),
        ),
    ]
