# Generated by Django 4.2.21 on 2025-05-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='权限名称')),
                ('codename', models.CharField(max_length=128, unique=True, verbose_name='权限代码')),
                ('type', models.CharField(choices=[('api', '接口权限'), ('button', '按钮权限')], max_length=8, verbose_name='权限类型')),
                ('method', models.CharField(blank=True, max_length=8, null=True, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='接口路径')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
    ]
