# Generated by Django 4.2.21 on 2025-05-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='type',
            field=models.CharField(choices=[('api', '按钮权限'), ('menu', '菜单权限')], max_length=8, verbose_name='权限类型'),
        ),
    ]
